image:
  file: .gitpod.Dockerfile
tasks:
  - init: mkdir -p build/vl && mkdir -p build/occ && 
      (cd vl && cmake ../../external/Visualization_Library 
        -DCMAKE_BUILD_TYPE=Release 
        -DVL_GUI_GLFW_SUPPORT=ON 
        -DVL_GUI_GLFW_EXAMPLES=OFF
        -DVL_INSTALL_DATA=ON 
        -DCMAKE_INSTALL_PREFIX=/workspace/vl-sdk 
        -Wno-dev && 
      cmake --build . --target install --config Release -- -j 16) &&
      (cd occ && cmake ../../ 
        -DCMAKE_BUILD_TYPE=Release 
        -DVL_ROOT=/workspace/vl-sdk 
        -DCMAKE_INSTALL_PREFIX=/workspace/occ-app
        -DWin32App=OFF
        -Wno-dev
      cmake --build . --target install --config Release -- -j 16)
    command: (cd /workspace/occ-app/bin/ && LD_LIBRARY_PATH="../lib" ./occlusion-culling-visualization 1200 1600)
ports:
  - port: 8000
    onOpen: open-preview