image:
  file: .gitpod.Dockerfile
tasks:
  - init: (cd external/Visualization_Library && ls -al && git apply ../../patches/vl.diff) && (cd src && ls -al && git apply ../patches/occ.diff) && 
      mkdir -p /workspace/build/vl && mkdir -p /workspace/build/occ && 
      (cd /workspace/build/vl && 
       cmake ../../occlusion-culling-visualization/external/Visualization_Library -DCMAKE_BUILD_TYPE=Release -DVL_GUI_GLFW_SUPPORT=ON -DVL_GUI_GLFW_EXAMPLES=OFF -DVL_INSTALL_DATA=ON -DCMAKE_INSTALL_PREFIX=/workspace/vl-sdk -Wno-dev &&
       cmake --build . --target install -- -j 16) &&
      (cd /workspace/build/occ && 
       cmake ../../occlusion-culling-visualization -DCMAKE_BUILD_TYPE=Release -DVL_ROOT=/workspace/vl-sdk -DCMAKE_INSTALL_PREFIX=/workspace/occ-app -DWin32App=OFF -Wno-dev &&
       cmake --build . --target install -- -j 16)
    command: (cd /workspace/occ-app/bin/ && LD_LIBRARY_PATH="../lib" ./occlusion-culling-visualization 1200 1600)
ports:
  - port: 8000
    onOpen: open-preview