image:
  file: .gitpod.Dockerfile
tasks:
  - command: mkdir build && cd build && export build_dir=`pwd` && mkdir vl && mkdir occ && 
      cd vl && cmake ../../external/Visualization_Library 
        -DCMAKE_BUILD_TYPE=Release 
        -DVL_GUI_GLFW_SUPPORT=ON 
        -DVL_INSTALL_DATA=ON 
        -DCMAKE_INSTALL_PREFIX=$build_dir/vl-sdk 
        -Wno-dev && 
      cmake --build . --target install --config Release &&
      cd ../ &&
      cd occ && cmake ../../ 
        -DCMAKE_BUILD_TYPE=Release 
        -DVL_ROOT=$build_dir/vl-sdk 
        -DCMAKE_INSTALL_PREFIX=$build_dir/occ-app 
        -Wno-dev
      cmake --build . --target install --config Release
      
ports:
  - port: 8000
    onOpen: open-preview