image:
  file: .gitpod.Dockerfile
tasks:
  - init: mkdir build && cd build && export build_dir=`pwd` && mkdir vl && mkdir occ && 
      cd vl && cmake ../../external/Visualization_Library 
        -DCMAKE_BUILD_TYPE=Release 
        -DVL_GUI_GLFW_SUPPORT=ON 
        -DVL_GUI_GLFW_EXAMPLES=OFF
        -DVL_INSTALL_DATA=ON 
        -DCMAKE_INSTALL_PREFIX=$build_dir/vl-sdk 
        -Wno-dev && 
      cmake --build . --target install --config Release &&
      cd ../ &&
      cd occ && cmake ../../ 
        -DCMAKE_BUILD_TYPE=Release 
        -DVL_ROOT=$build_dir/vl-sdk 
        -DCMAKE_INSTALL_PREFIX=$build_dir/occ-app 
        -DWin32App=OFF
        -Wno-dev
      cmake --build . --target install --config Release
  - command: (cd build/occ-app/bin/ && LD_LIBRARY_PATH="../lib" ./occlusion-culling-visualization 1200 1600)
ports:
  - port: 8000
    onOpen: open-preview